name: ChestSetUP_KJ
main: com.kj.chestsetup.ChestSetup
version: 1.0
api-version: 1.20
commands:
  chestsetup:
    description: チェストの設置・削除を行います（OP専用）
    usage: /chestsetup <set|remove|removeall> [チェスト名]
    tab-complete: true
