name: Java CI with Gradle

on:
  push:
    tags:
      - 'v*.*.*'  # バージョンタグがプッシュされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # すべての履歴とタグを取得

      - name: JDK 17のセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradleのセットアップ
        uses: gradle/gradle-build-action@v2

      - name: Gradleに実行権限を付与
        run: chmod +x ./gradlew

      - name: ビルド
        run: ./gradlew build

      - name: プロジェクト情報の取得
        id: project_info
        run: |
          echo "name=ChestSetup_KJ" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: JARファイルのアップロード
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: build/libs/ChestSetup_KJ-*.jar

      - name: リリースの作成
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: リリースにアセットをアップロード
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/ChestSetup_KJ-${{ env.version }}.jar
          asset_name: ChestSetup_KJ-${{ env.version }}.jar
          asset_content_type: application/java-archive

      - name: セマンティックバージョンタグの更新
        uses: tchupp/actions-update-semver-tags@v1
