name: Java CI with Gradle

on:
  push:
    tags:
      - 'v*.*.*'  # バージョンタグがプッシュされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # リリース作成に必要な権限を追加

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # すべての履歴とタグを取得

      - name: JDK 17のセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradleラッパーの生成を最初に行う
      - name: Gradleラッパーの生成
        run: gradle wrapper
        
      - name: Gradleに実行権限を付与
        run: chmod +x ./gradlew

      - name: ビルド
        run: ./gradlew build

      - name: プロジェクト情報の取得
        id: project_info
        run: |
          echo "name=ChestSetup_KJ" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "jar_path=$(find build/libs -name "*.jar" | head -n 1)" >> $GITHUB_ENV

      - name: JARファイルの確認
        run: |
          echo "Found JAR file: ${{ env.jar_path }}"
          ls -la build/libs/

      - name: JARファイルのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/*.jar
          retention-days: 5

      - name: リリースの作成とアセットのアップロード
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: セマンティックバージョンタグの更新
        uses: tchupp/actions-update-semver-tags@v1
